#!/usr/bin/env bash
# chimpworks one-shot machine setup: isolated venv + vendored models + config.
# Idempotent -- safe to re-run. Only network use here is pip + Hugging Face
# downloads; after this, `chimpworks` runs offline (HF_HUB_OFFLINE=1).
#
#   ./scripts/setup_models.sh                 # small model only
#   WHISPER_SIZES="small large-v3" ./scripts/setup_models.sh
#   CHIMPWORKS_HF_TOKEN=hf_xxx ./scripts/setup_models.sh   # first run / re-vendor
#
# The pyannote pipeline repo is gated: the token's HF account must have accepted
#   https://huggingface.co/pyannote/speaker-diarization-community-1
set -euo pipefail

SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENV="${CHIMPWORKS_VENV:-$HOME/.local/share/chimpworks/venv}"
MODELS_DIR="$HOME/.local/share/chimpworks/models"
DIAR_DIR="$MODELS_DIR/pyannote-community-1"
CONFIG="$HOME/.config/chimpworks/config.toml"
WHISPER_SIZES="${WHISPER_SIZES:-small}"
PY="$VENV/bin/python"

echo "==> venv: $VENV"
if [ ! -x "$PY" ]; then
    python3 -m venv "$VENV"
fi
"$PY" -m pip install -q --upgrade pip
if [ -f "$SRC_DIR/requirements.lock" ]; then
    "$PY" -m pip install -q -r "$SRC_DIR/requirements.lock" -e "$SRC_DIR"
else
    "$PY" -m pip install -q -e "$SRC_DIR"[diarize]
fi

echo "==> diarization pipeline: $DIAR_DIR"
if [ -f "$DIAR_DIR/config.yaml" ]; then
    echo "    already vendored, skipping"
else
    : "${CHIMPWORKS_HF_TOKEN:?set CHIMPWORKS_HF_TOKEN to vendor the gated pyannote repo}"
    mkdir -p "$DIAR_DIR"
    "$PY" - "$DIAR_DIR" <<'PY'
import os, sys
from huggingface_hub import snapshot_download
snapshot_download(
    "pyannote/speaker-diarization-community-1",
    token=os.environ["CHIMPWORKS_HF_TOKEN"],
    local_dir=sys.argv[1],
    allow_patterns=["*.yaml", "*.bin", "*.npz", "*.md"],
)
print("    vendored ok")
PY
fi

echo "==> whisper sizes: $WHISPER_SIZES"
for size in $WHISPER_SIZES; do
    HF_HUB_OFFLINE=0 "$PY" - "$size" <<'PY'
import sys
from faster_whisper import WhisperModel
WhisperModel(sys.argv[1], device="cpu", compute_type="int8")
print(f"    cached {sys.argv[1]}")
PY
done

echo "==> config: $CONFIG"
if [ -f "$CONFIG" ]; then
    echo "    exists, leaving as-is"
else
    mkdir -p "$(dirname "$CONFIG")"
    cat > "$CONFIG" <<EOF
# chimpworks configuration (generated by scripts/setup_models.sh).
output_dir = ""
default_topic = "General"
model = "$(echo "$WHISPER_SIZES" | awk '{print $1}')"
language = "auto"
device = "auto"
compute_type = "auto"
word_timestamps = true
formats = ["txt", "srt", "vtt", "json"]
make_article = false
make_citation = true
citation_style = "apa"
digest = "heuristic"
diarize = false
diarize_model = "$DIAR_DIR/config.yaml"
yt_cookies_from_browser = ""
EOF
    echo "    written"
fi

echo "==> doctor"
if [ -x "$HOME/.local/bin/chimpworks" ]; then
    "$HOME/.local/bin/chimpworks" doctor
else
    echo "    (no ~/.local/bin/chimpworks launcher found -- see scripts/chimpworks.wrapper)"
fi
echo "==> done"
