"""Write chimpworks/_build.py from environment, just before a release build.

    CHIMPWRITER_LICENCE_URL   https://chimpwriter-licensing.<acct>.workers.dev
    CHIMPWRITER_ENFORCE       "1" / "true" to gate Pro features
    CHIMPWRITER_TRUSTED_KEYS  JSON object: {"lease-2026a": "<b64>", "cert-2026a": "<b64>"}

CI sets these from repo secrets. Locally, running with none set restores the
inert dev copy, which is what should be committed.
"""
import json
import os
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
TARGET = ROOT / "chimpworks 1-2" / "chimpworks" / "_build.py"

url = os.environ.get("CHIMPWRITER_LICENCE_URL", "").strip()
enforce_raw = os.environ.get("CHIMPWRITER_ENFORCE", "").strip()
keys_raw = os.environ.get("CHIMPWRITER_TRUSTED_KEYS", "").strip()

if not (url or enforce_raw or keys_raw):
    print(f"no release config in env — leaving {TARGET.name} as committed (dev/inert)")
    raise SystemExit(0)

enforce = enforce_raw.lower() in ("1", "true", "yes")
keys = json.loads(keys_raw) if keys_raw else {}
if keys and not isinstance(keys, dict):
    raise SystemExit("CHIMPWRITER_TRUSTED_KEYS must be a JSON object")

body = (
    '"""Build-time configuration. Generated by packaging/write_build_config.py."""\n'
    "from __future__ import annotations\n\n"
    f"LICENCE_URL: str = {url!r}\n"
    f"ENFORCE: bool = {enforce!r}\n"
    f"TRUSTED_KEYS: dict[str, str] = {json.dumps(keys, indent=4) if keys else '{}'}\n"
)
TARGET.write_text(body, encoding="utf-8")
print(f"wrote {TARGET}")
print(f"  LICENCE_URL = {url or '(empty — unconfigured)'}")
print(f"  ENFORCE     = {enforce}")
print(f"  TRUSTED_KEYS: {len(keys)} key(s)")
